[package]
name = "avs-oracle"
version = "0.1.0"
description = "AVS Oracle task management and verification"
edition = "2021"
license = "Apache-2.0"
authors = ["Bristin Borah <bristinozon@gmail.com>"]
repository = "https://github.com/wildchain/ozon_contract"

[lib]
crate-type = ["cdylib", "lib"]
name = "avs_oracle"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
pyth-solana-receiver-sdk = "1.0.1"
restaking-programs = { path = "../restaking-programs", features = ["cpi"] }
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1" }
zeroize = "1.3.0"
proc-macro2 = "1.0.70"
