[package]
name = "restaking-programs"
version = "0.1.0"
description = "Ozon Restaking Solana Program that is responsible for restaking user tokens to Ozon protocol. It also comes up with onchain instructions to manage and register operators and AVSs with the Ozon protocol."
edition = "2021"
authors = ["Bristin Borah  bristinozon@gmail.com"]

[lib]
crate-type = ["cdylib", "lib"]
name = "restaking_programs"

[features]
default = ["idl-build"]
anchor-debug = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]


[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1" }
zeroize = "1.3.0"
proc-macro2 = "1.0.70"
pyth-solana-receiver-sdk = "1.0.1"
restaking_programs = "0.1.0"
