[package]
name = "ozon-cli"
version = "0.1.27"
edition = "2021"
authors = ["Bristin Borah  <bristinozon@gmail.com>"]
description = "Ozon CLI helps to manage and register operators and AVSs with the Ozon protocol."
license = "Apache-2.0"
repository = "https://github.com/wildchain/ozon_contract"
homepage = "https://github.com/wildchain/ozon_contract"
readme = "README.md"
keywords = ["solana", "ozon", "cli", "restaking", "programs"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anchor-client = "0.31.1"
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
restaking-programs = { version = "0.1.4" }
dirs = "5"
open = "5.3.2"
tokio = { version = "1.35", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "blocking"] }
avs-oracle = { version = "0.1.10" }
hex = "0.4"
operator-nodes-client = { version = "0.1.0" }

[[bin]]
name = "ozon-cli"
path = "src/main.rs"
